# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'rspec', :require => 'spec'
gem 'guard'
gem 'win32console' if Gem.win_platform?
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'guard-rspec', require: false
